# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
gems: ["jekyll-paginate"]

collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

#Pageination
paginate: 5
paginate_path: "/blog/page:num/"




title: Jessica Engström's blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://catoholic.se" # the base hostname & protocol for your site
twitter_username: grytlappen
facebook_username: EngstromJessica
googleplus_username: 103526937978144763696
linkedin_username: jessicaengstrom
github_username:  jekyll
blogname: Jessica Engström
subtitle: The girl with the Batman/Spider-Man tattoo
googleanalytics: UA-45661394-2
googleanalytics_site: grytlappen.se 
# Build settings
markdown: kramdown


url: http://localhost:4000

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
  -
    scope:
      path: "project"
    values:
      layout: project